### ISSUE TITLE
TinyPDF or jpeg.rocks

### ISSUE THREAD

**Issue by Dreadaxe** [SCOTPAUL/ImageCompressorForDiscord#1]
Which image compressor algorithm do you use? TinyPDF ? jpeg.rocks ? Other ?

**Comment by SCOTPAUL** [comment]
I used [this library](https://github.com/zetbaitsu/Compressor) which calls Android's native [Bitmap.compress](https://developer.android.com/reference/android/graphics/Bitmap#compress(android.graphics.Bitmap.CompressFormat,%20int,%20java.io.OutputStream)) method under-the-hood to compress the image as a jpeg.
